version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: laravel/framework
    versions:
    - ">= 6.a, < 7"
  - dependency-name: phpunit/phpunit
    versions:
    - ">= 8.a, < 9"
  - dependency-name: phpunit/phpunit
    versions:
    - ">= 9.a, < 10"
